---
  - name: getapache
    hosts: linux,database
    become: yes
    become_method: sudo
    become_user: root


    tasks:
      - name: install apache and php
        apt:
          name: 
          - apache2
          - php5-cli
          state: latest